### ISSUE TITLE
YAML exception

### ISSUE THREAD

**Issue by RitikaGeraMicrosoft** [bendrucker/cfn-nest#18]
I am parsing my well-formed json swagger using oav validate-spec and getting the above mentioned error. There are no syntax errors. Anything else that might cause this issue ?

```
fatal error: unacceptable kind of an object to dump [object Error], {"name":"YAMLException","reason":"unacceptable kind of an object to dump [object Error]","message":"unacceptable kind of an object to dump [object Error]"}
```

**Comment by bendrucker** [comment]
Hi there, I'll need example configuration that I can test to look into this.
